---
title: "The exploration's report"
date: "August, 2019"
---

```{r setup_exploration, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos =  "h")
knitr::opts_knit$set(root.dir = "../")

```

```{r scripts_exploration, include=FALSE}
# loading required steps before performing the analysis
source("./src/util/auxiliary_functions.R")
source("./src/datapreparation/execute_data_preparation.R")
```

# Exploration 1

Describe your exploration 1 here, including some plots, tables or any resource used.

```{r exploration_target_1, echo=TRUE, out.width = '100%'}
# your code with the exploration 1 goes here
```

# Exploration 2

Describe your exploration 2 here, including some plots, tables or any resource used.

```{r exploration_target_2, echo=TRUE, out.width = '100%'}
# your code with the exploration 2 goes here
```


# Exploration 3

Describe your exploration 3 here, including some plots, tables or any resource used.

```{r exploration_target_3, echo=TRUE, out.width = '100%'}
# your code with the exploration 3 goes here
```

